### PR TITLE
httpURLConnection.getErrorStream() can return null so handle it.

### PR DESCRIPTION
**Pull request by brycechesternewman**
Fixes https://github.com/jopenlibs/vault-java-driver/issues/30

### CODE REVIEW

**Comment by brycechesternewman** [comment]
Hi @henryx or @tledkov. 
Can I please get some eyes on this PR?

**Comment by brycechesternewman** [comment]
@henryx howdy. Can you have another look please?

**Comment by brycechesternewman** [comment]
@henryx Thank you for merging. What is your typical release schedule? I want to make use of this asap. Thanks again.

**Comment by henryx** [comment]
I've released [new version](https://github.com/jopenlibs/vault-java-driver/releases/tag/v5.4.0) with this patch. For some reasons, publishing to Maven Central is a bit slow. If you need asap this release, you can use [jitpack.io](https://jitpack.io) as as alternate package repository

**Comment by brycechesternewman** [comment]
I am not yet seeing 4.5.0 published to maven central. Are you?

**Pull request merged**
